### ISSUE TITLE
Cannot read property 'validators' of undefined

### ISSUE THREAD

**Issue by bgulotta** [tjwebb/sails-backbone-client#4]
I am getting the above error attempting to use BackboneClient. I am using browserify to package and include BackboneClient in my client side app.

    _.extend(Backbone.Validation.validators, anchorRules, associationRules(ns));

**Comment by tjwebb** [comment]
Can you share your code? I'll try to reproduce this

**Comment by bgulotta** [comment]
The following text below is getting bundled up with a browserify command and the resulting .js file is included in the body of the page.

/**
 * Created by bgulotta on 2/26/15.
 */
var BackboneClient = require('sails-backbone-client');
BackboneClient.create('localhost:1337/backbonemodel', {}).then(function (api) {
    window.api = api;
});

**Comment by bgulotta** [comment]
The following text below is getting bundled up with a browserify command and the resulting .js file is included in the body of the page.

```
var BackboneClient = require('sails-backbone-client');
BackboneClient.create('localhost:1337/backbonemodel', {}).then(function (api) {
    window.api = api;
});
```

**Comment by tjwebb** [comment]
Maybe Backbone.Validation isn't being included in your browserify bundle for some reason? I do the same thing here with browserify and everything works fine: https://github.com/hashware/backbone-client/blob/master/index.js#L4.

It's browserified as part of this module: https://github.com/hashware/hashpanel/blob/master/lib/index.js#L16

One difference is that I'm using gulp? But that shouldn't matter. Any information would help; I'm at a loss.

**Comment by bgulotta** [comment]
Yeah man I'm not sure either. I'm using version 0.11.4 of sails-backbone-client. I'll take a look at your test and see if there is something else I may need to require before bundling it up with browserify or try using gulp.

**Comment by bgulotta** [comment]
i got the client to work by updating my requires as follows

```
var Backbone = require('backbone');
Backbone.ajax = require('backbone.ajax');
var BackboneClient = require('sails-backbone-client');

var sdk = {};
BackboneClient.create('http://127.0.0.1:1337/backbonemodel', sdk).then(function (api) {
    window.api = api;
});


```

**Comment by tjwebb** [comment]
Ok. I'll look into this and see if I can make this less problematic. Thanks.

**Comment by tjwebb** [comment]
I shoul
