### ISSUE TITLE
backbone model created from sails-backbone-client not validating?

### ISSUE THREAD

**Issue by bgulotta** [tjwebb/sails-backbone-client#5]
I've copied and modified your test file so that I can make sure validations are working on the backbone model that gets generated from the sailsjs model. I'm testing the attribute below that is on my sailsjs model. When I create a new instance of my backbone user model and call validate() it isn't failing validation.

```
    name: { type: 'string', required: true },
```

**Comment by tjwebb** [comment]
https://github.com/tjwebb/sails-backbone-client/blob/master/test.js#L111-L119

This process seems to work for me. If I remove the `name` field from that model, for example, my validation fails.

**Comment by bgulotta** [comment]
Do you think my issue has anything to do with this section in parser.js? It appears that the actual validations are sitting off a json property.

```
var instanceMethods = {
  defaults: function () {
    return _.cloneDeep(this._defaults);
  },
  validation: function () {

    return _.cloneDeep(this._validation);
  }
};

-- should the above get changed to :

var instanceMethods = {
  defaults: function () {
    return _.cloneDeep(this.json._defaults);
  },
  validation: function () {

    return _.cloneDeep(this.json._validation);
  }

```

**Comment by tjwebb** [comment]
Where does the `.json` come from? Can you post some more of your code

**Comment by tjwebb** [comment]
btw, added invalidation test (which passes):
https://github.com/tjwebb/sails-backbone-client/blob/master/test.js#L121-L133

**Comment by tjwebb** [comment]
Ah, re `json` property:

Are you using this controller? https://github.com/tjwebb/sails-backbone/blob/master/api/controllers/BackboneModelController.js#L12-L21

It should have been generated into your project

**Comment by bgulotta** [comment]
yeah my controller was empty. i deleted and re-installed the sails-generator and am getting output that matches what the sails-backbone-client is expecting

**Comment by tjwebb** [comment]
Did you have any issues when you ran the generator?

Let me know if you have any other issues. Closing.

**Comment by bgulotta** [comment]
Thx man. I have everything working now. Do you know off the top of your head if you an customize the validation error messages? Right now i'm just getting generic error messages like "failed "required" validation" displayed on my site.

**Comment by tjwebb** [comment]
Yea, you should be able to override any of the validators according to the Backbone.Validation spec: https://github.com/thedersen/backbone.validation#specifying-error-messages

Specifically, e.g. for an attribute called `name` that means you can try setting `this._validation.name.msg` to some string.
